"""initial migration

Revision ID: 415cf0869451
Revises: 73946e050aaf
Create Date: 2024-10-16 11:16:59.289919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415cf0869451'
down_revision = '73946e050aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date_of_birth', table_name='student__register')
    op.drop_index('last_name', table_name='student__register')
    op.drop_index('level', table_name='student__register')
    op.drop_index('local_govt_area', table_name='student__register')
    op.drop_index('other_name', table_name='student__register')
    op.drop_index('parent_guardian_address', table_name='student__register')
    op.drop_index('parent_guardian_name', table_name='student__register')
    op.drop_index('place_of_birth', table_name='student__register')
    op.drop_index('residential_address', table_name='student__register')
    op.drop_index('state_of_origin', table_name='student__register')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_of_origin', 'student__register', ['state_of_origin'], unique=True)
    op.create_index('residential_address', 'student__register', ['residential_address'], unique=True)
    op.create_index('place_of_birth', 'student__register', ['place_of_birth'], unique=True)
    op.create_index('parent_guardian_name', 'student__register', ['parent_guardian_name'], unique=True)
    op.create_index('parent_guardian_address', 'student__register', ['parent_guardian_address'], unique=True)
    op.create_index('other_name', 'student__register', ['other_name'], unique=True)
    op.create_index('local_govt_area', 'student__register', ['local_govt_area'], unique=True)
    op.create_index('level', 'student__register', ['level'], unique=True)
    op.create_index('last_name', 'student__register', ['last_name'], unique=True)
    op.create_index('date_of_birth', 'student__register', ['date_of_birth'], unique=True)
    # ### end Alembic commands ###
