"""empty message

Revision ID: 66537a8f2fe5
Revises: 8752f8a3ad06
Create Date: 2024-11-20 20:37:42.476385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66537a8f2fe5'
down_revision = '8752f8a3ad06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_fee', sa.Column('level_id', sa.Integer(), nullable=False))
    op.add_column('school_fee', sa.Column('session_id', sa.Integer(), nullable=False))
    op.drop_constraint('school_fee_ibfk_8', 'school_fee', type_='foreignkey')
    op.create_foreign_key(None, 'school_fee', 'session', ['session_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'level', ['level_id'], ['id'])
    op.drop_column('school_fee', 'student_register_id')
    op.drop_column('school_fee', 'level')
    op.create_foreign_key(None, 'student_register', 'level', ['level_id'], ['id'])
    op.create_foreign_key(None, 'student_register', 'session', ['session_id'], ['id'])
    op.drop_column('student_register', 'session')
    op.drop_column('student_register', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_register', sa.Column('level', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('student_register', sa.Column('session', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.add_column('school_fee', sa.Column('level', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('school_fee', sa.Column('student_register_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.create_foreign_key('school_fee_ibfk_8', 'school_fee', 'student_register', ['student_register_id'], ['id'])
    op.drop_column('school_fee', 'session_id')
    op.drop_column('school_fee', 'level_id')
    # ### end Alembic commands ###
