"""empty message

Revision ID: 73946e050aaf
Revises: 95cf7297d6e6
Create Date: 2024-10-07 16:47:00.900428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73946e050aaf'
down_revision = '95cf7297d6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student__register', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('student__register', sa.Column('verification_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student__register', 'verification_code')
    op.drop_column('student__register', 'verified')
    # ### end Alembic commands ###
