"""Sync migrations

Revision ID: 779a39a651ee
Revises: ee99579b75ac
Create Date: 2024-11-17 14:39:58.568386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '779a39a651ee'
down_revision = 'ee99579b75ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    op.drop_table('courses')
    op.add_column('school_fee', sa.Column('programme_id', sa.Integer(), nullable=False))
    op.add_column('school_fee', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('school_fee', sa.Column('student_register_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'school_fee', 'programme', ['programme_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'student_register', ['student_register_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'department', ['department_id'], ['id'])
    op.drop_column('school_fee', 'academic_session')
    op.drop_column('school_fee', 'program')
    op.drop_column('school_fee', 'created_at')
    op.drop_column('school_fee', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_fee', sa.Column('level', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('school_fee', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('school_fee', sa.Column('program', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('school_fee', sa.Column('academic_session', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_column('school_fee', 'student_register_id')
    op.drop_column('school_fee', 'department_id')
    op.drop_column('school_fee', 'programme_id')
    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('credit_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('student_courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_register_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_registered', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_courses_ibfk_2'),
    sa.ForeignKeyConstraint(['student_register_id'], ['student_register.id'], name='student_courses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
