"""Sync migrations

Revision ID: 8752f8a3ad06
Revises: e90e002d60fd
Create Date: 2024-11-19 18:50:35.807724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8752f8a3ad06'
down_revision = 'e90e002d60fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'school_fee', 'programme', ['programme_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'student_register', ['student_register_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'department', ['department_id'], ['id'])
    op.drop_column('school_fee', 'created_at')
    op.add_column('student_register', sa.Column('level_id', sa.Integer(), nullable=False))
    op.add_column('student_register', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_register', 'session', ['session_id'], ['id'])
    op.create_foreign_key(None, 'student_register', 'level', ['level_id'], ['id'])
    op.drop_column('student_register', 'session')
    op.drop_column('student_register', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_register', sa.Column('level', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('student_register', sa.Column('session', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.drop_column('student_register', 'session_id')
    op.drop_column('student_register', 'level_id')
    op.add_column('school_fee', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    # ### end Alembic commands ###
