"""Initial migration

Revision ID: 95cf7297d6e6
Revises: 
Create Date: 2024-10-07 16:22:20.603066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cf7297d6e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin__register', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('admin__register', sa.Column('verification_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin__register', 'verification_code')
    op.drop_column('admin__register', 'verified')
    # ### end Alembic commands ###
