"""empty message

Revision ID: e8ab3f53b6b2
Revises: e6d6bab80169
Create Date: 2024-11-20 21:19:47.918603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8ab3f53b6b2'
down_revision = 'e6d6bab80169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('school_fee_ibfk_11', 'school_fee', type_='foreignkey')
    op.create_foreign_key(None, 'school_fee', 'level', ['level_id'], ['id'])
    op.create_foreign_key(None, 'school_fee', 'session', ['session_id'], ['id'])
    op.drop_column('school_fee', 'student_register_id')
    op.drop_column('school_fee', 'level')
    op.create_foreign_key(None, 'student_register', 'level', ['level_id'], ['id'])
    op.create_foreign_key(None, 'student_register', 'session', ['session_id'], ['id'])
    op.drop_column('student_register', 'level')
    op.drop_column('student_register', 'session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_register', sa.Column('session', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('student_register', sa.Column('level', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.drop_constraint(None, 'student_register', type_='foreignkey')
    op.add_column('school_fee', sa.Column('level', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('school_fee', sa.Column('student_register_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.drop_constraint(None, 'school_fee', type_='foreignkey')
    op.create_foreign_key('school_fee_ibfk_11', 'school_fee', 'student_register', ['student_register_id'], ['id'])
    # ### end Alembic commands ###
